// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ungoomrisqydakvztqcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZ29vbXJpc3F5ZGFrdnp0cWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDkxMjAsImV4cCI6MjA2OTYyNTEyMH0.AVKo5XqQwot3KH9k8BZXR49q2UFaDD7rWcuk0Q0-0Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});